# Generated by Django 2.2 on 2019-06-06 09:11

from django.db import migrations
import tagging_autocomplete_new.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255, null=True),
        ),
    ]
