# Generated by Django 2.2 on 2019-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190606_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус'),
        ),
    ]
