# Generated by Django 2.2 on 2019-05-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190513_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tag1', to='articles.Tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tag2', to='articles.Tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tag3', to='articles.Tag', verbose_name='Тег'),
        ),
    ]
