# Generated by Django 2.2 on 2019-06-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('articles', '0003_auto_20190610_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='companies.Company', verbose_name='Компания'),
        ),
    ]
