# Generated by Django 2.2 on 2019-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190610_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='activity',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Деятельность'),
        ),
    ]
