# Generated by Django 2.2 on 2019-05-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190513_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0, max_length=10, verbose_name='Рейтинг'),
        ),
    ]
