# Generated by Django 2.2 on 2019-06-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190611_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='activity',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='companies.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Статус'),
        ),
    ]
