# Generated by Django 2.2 on 2019-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190513_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag1',
        ),
        migrations.AddField(
            model_name='article',
            name='tag1',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='articles.Tag', verbose_name='Тег'),
        ),
    ]
