# Generated by Django 2.2 on 2019-05-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190513_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tag1',
            field=models.ManyToManyField(to='articles.Tag', verbose_name='Тег(и)'),
        ),
    ]
