# Generated by Django 2.2 on 2019-05-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190513_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag3',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.Tag', verbose_name='Теги'),
        ),
    ]
