# Generated by Django 2.2 on 2019-05-13 07:01

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20190513_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_height',
            field=models.IntegerField(default=400, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_width',
            field=models.IntegerField(default=400, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default=400, verbose_name='Высота'), null=True, upload_to=articles.models.get_image_path, verbose_name='Изображение', width_field=models.IntegerField(default=400, verbose_name='Ширина')),
        ),
    ]
