# Generated by Django 2.2 on 2019-05-13 07:04

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20190513_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(), null=True, upload_to=articles.models.get_image_path, verbose_name='Изображение', width_field=models.PositiveIntegerField()),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_width',
            field=models.PositiveIntegerField(),
        ),
    ]
