# Generated by Django 2.2 on 2019-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20190513_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='get_image_path', verbose_name='Изображение', width_field='image_width'),
        ),
    ]
