# Generated by Django 2.2 on 2019-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20190513_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='get_image_path', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Tag', verbose_name='Теги'),
        ),
    ]
