# Generated by Django 2.2 on 2019-05-13 08:20

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190513_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.get_image_path, verbose_name='Изображение'),
        ),
    ]
