# Generated by Django 2.2 on 2019-05-14 05:26

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='account_image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.get_image_path, verbose_name='Аватар'),
        ),
    ]
