# Generated by Django 2.2 on 2019-05-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20190514_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='name',
        ),
    ]
