# Generated by Django 2.2 on 2019-05-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20190514_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='articles.Gender', verbose_name='Пол'),
        ),
    ]
