# Generated by Django 2.2 on 2019-05-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20190514_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Гендер', 'verbose_name_plural': 'Гендеры'},
        ),
    ]
