# Generated by Django 2.2 on 2019-05-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20190514_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='card_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Аннотация'),
        ),
    ]
