# Generated by Django 2.2 on 2019-05-15 03:27

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20190515_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='card_text',
            field=models.CharField(blank=True, help_text='Введите до 200 символов.', max_length=200, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение на плитке на главной странице.\n                              Это поле проверяется первым.\n                              Если файл отсутствует - получает картинку по ссылке (ниже).', null=True, upload_to=articles.models.get_image_path, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Изображение на плитке на главной странице.', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
