# Generated by Django 2.2 on 2019-05-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20190515_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='card_text',
            field=models.TextField(blank=True, help_text='Введите до 200 символов.', max_length=200, null=True, verbose_name='Аннотация'),
        ),
    ]
