# Generated by Django 2.2 on 2019-05-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20190515_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0, max_length=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Введите до 50 символов.', max_length=50, verbose_name='Название статьи'),
        ),
    ]
