# Generated by Django 2.2 on 2019-05-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_auto_20190515_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество проголосовавших'),
        ),
    ]
