# Generated by Django 2.2 on 2019-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_article_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Количество проголосовавших'),
        ),
    ]
