# Generated by Django 2.2 on 2019-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20190515_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Рейтинг'),
        ),
    ]
