# Generated by Django 2.2 on 2019-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20190515_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_rating',
            field=models.IntegerField(default=0, help_text='Всего баллов, полученных от поьзователей', verbose_name='Всего баллов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0, help_text='Текущий рейтинг в 5-ти балльной шкале', verbose_name='Текущий рейтинг'),
        ),
    ]
