# Generated by Django 2.2 on 2019-05-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_auto_20190515_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0, help_text='Текущий рейтинг в 5-ти балльной шкале', max_length=2, verbose_name='Текущий рейтинг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='total_rating',
            field=models.IntegerField(default=0, help_text='Всего баллов, полученных от пользователей', verbose_name='Всего баллов'),
        ),
    ]
