# Generated by Django 2.2 on 2019-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0039_auto_20190515_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
