# Generated by Django 2.2 on 2019-05-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('articles', '0040_article_session'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.CreateModel(
            name='ArticleStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('total_rating', models.IntegerField(default=0, help_text='Всего баллов, полученных от пользователей', verbose_name='Всего баллов')),
                ('rating', models.FloatField(default=0, help_text='Текущий рейтинг в 5-ти балльной шкале', max_length=1, verbose_name='Текущий рейтинг')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Количество проголосовавших')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'db_table': 'article_statistics',
            },
        ),
    ]
