# Generated by Django 2.2 on 2019-05-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('articles', '0041_auto_20190516_1627'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
