# Generated by Django 2.2 on 2019-05-16 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_auto_20190516_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestatistics',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='articlestatistics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
