# Generated by Django 2.2 on 2019-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0043_auto_20190516_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0, help_text='Текущий рейтинг в 5-ти балльной шкале', max_length=1, verbose_name='Текущий рейтинг'),
        ),
        migrations.AddField(
            model_name='article',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Количество проголосовавших'),
        ),
        migrations.AddField(
            model_name='article',
            name='total_rating',
            field=models.IntegerField(default=0, help_text='Всего баллов, полученных от пользователей', verbose_name='Всего баллов'),
        ),
        migrations.DeleteModel(
            name='ArticleStatistics',
        ),
    ]
