# Generated by Django 2.2 on 2019-05-16 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rated_users',
            field=models.ManyToManyField(blank=True, related_name='rated_users', to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавшие пользователи'),
        ),
        migrations.AddField(
            model_name='article',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, читавшие статью'),
        ),
    ]
