# Generated by Django 2.2 on 2019-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0046_auto_20190516_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Введите до 100 символов.', max_length=100, verbose_name='Название статьи'),
        ),
    ]
