# Generated by Django 2.2 on 2019-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0047_auto_20190522_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='session',
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.TextField(blank=True, help_text='Изображение на плитке на главной странице.', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
