# Generated by Django 2.2 on 2019-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0049_auto_20190522_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.TextField(blank=True, help_text='Изображение на плитке на главной странице.', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
