# Generated by Django 2.2 on 2019-05-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0050_auto_20190522_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating_count',
        ),
    ]
