# Generated by Django 2.2 on 2019-06-03 03:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0051_remove_article_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Страна'),
        ),
    ]
