# Generated by Django 2.2 on 2019-06-03 03:50

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0052_advuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='account_image_url',
            field=models.URLField(blank=True, help_text='Вы можете либо загрузить картинку, либо вставить ссылку на нее.', null=True, verbose_name='Ссылка на изображение профиля'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='account_image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.get_image_path, verbose_name='Изображение профиля'),
        ),
    ]
