# Generated by Django 2.2 on 2019-06-03 04:24

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_auto_20190603_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='short_name',
            field=models.CharField(db_index=True, default=None, max_length=1, unique=True, verbose_name='Название пола в одну букву.'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='account_image',
            field=models.ImageField(blank=True, help_text='Лучше всего подобрать картинку с соотношением сторон 4:3.', null=True, upload_to=articles.models.get_image_path, verbose_name='Изображение профиля'),
        ),
    ]
