# Generated by Django 2.2 on 2019-06-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0054_auto_20190603_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='short_name',
            field=models.CharField(db_index=True, default=None, max_length=1, unique=True, verbose_name='Название пола в одну букву. Используется в коде.'),
        ),
    ]
