# Generated by Django 2.2 on 2019-06-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0055_auto_20190603_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='short_name',
            new_name='one_letter_name',
        ),
    ]
