# Generated by Django 2.2 on 2019-06-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0058_auto_20190603_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='one_letter_name',
        ),
    ]
