# Generated by Django 2.2 on 2019-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0060_gender_one_letter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='one_letter_name',
            field=models.CharField(default=None, help_text='Используется в коде.', max_length=1, unique=True, verbose_name='Название пола в одну букву'),
        ),
    ]
