# Generated by Django 2.2 on 2019-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0061_auto_20190603_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='fb_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='ok_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='tw_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='vk_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ВКонтакте'),
        ),
    ]
