# Generated by Django 2.2 on 2019-06-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0063_auto_20190603_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='fb_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='ok_url',
            field=models.URLField(blank=True, default='', verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='tw_url',
            field=models.URLField(blank=True, default='', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='vk_url',
            field=models.URLField(blank=True, default='', verbose_name='ВКонтакте'),
        ),
    ]
