# Generated by Django 2.2 on 2019-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0064_auto_20190603_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='account_image_url',
            field=models.URLField(blank=True, default='', help_text='Вы можете либо загрузить картинку, либо вставить ссылку на нее.', verbose_name='Ссылка на изображение профиля'),
        ),
    ]
