# Generated by Django 2.2 on 2019-06-03 10:59

from django.db import migrations
import tagging_autocomplete.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0065_auto_20190603_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=tagging_autocomplete.models.TagAutocompleteField(blank=True, max_length=255),
        ),
    ]
