# Generated by Django 2.2 on 2019-06-04 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0066_auto_20190603_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='user_subscriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
