# Generated by Django 2.2 on 2019-06-04 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0067_advuser_user_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='user_subscriptions',
        ),
        migrations.AddField(
            model_name='advuser',
            name='user_subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='_advuser_user_subscriptions_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
