# Generated by Django 2.2 on 2019-06-04 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0068_auto_20190604_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='user_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='_advuser_user_subscriptions_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
