# Generated by Django 2.2 on 2019-06-04 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_adapt_max_tag_length'),
        ('articles', '0069_auto_20190604_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='tags_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='tags_subscriptions', to='tagging.Tag', verbose_name='Подписки на теги'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='user_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='_advuser_user_subscriptions_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки на пользователей'),
        ),
    ]
