# Generated by Django 2.2 on 2019-06-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0070_auto_20190604_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
