# Generated by Django 2.2 on 2019-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100, verbose_name='Название компании')),
                ('company_logo', models.ImageField(upload_to='', verbose_name='Логотип компании')),
                ('company_logo_url', models.URLField(verbose_name='Ссылка на логотип компании')),
                ('company_description', models.TextField(verbose_name='Описание компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
