# Generated by Django 2.2 on 2019-06-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Название компании'),
        ),
    ]
