# Generated by Django 2.2 on 2019-06-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190610_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo_url',
            new_name='logo_url',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
    ]
